apiVersion: v1
kind: Service
metadata:
  name: keda-demo-consumer-service
spec:
  type: NodePort  # Gunakan NodePort agar bisa diakses dari luar
  ports:
  - port: 8080    # Port yang digunakan oleh service
    targetPort: 8080  # Port yang digunakan oleh container
  selector:
    app: consumer  # Pastikan label ini sesuai dengan deployment