apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-demo-consumer-deployment
  labels:
    app: keda-demo-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-demo-consumer
  template:
    metadata:
      labels:
        app: keda-demo-consumer
    spec:
      containers:
        - name: keda-demo-consumer
          image: keda-demo-consumer:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          env:
            # - name: SR_API_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: api-secrets
            #       key: api_key
            # - name: SR_API_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: api-secrets
            #       key: api_secret
            - name: KAFKA_TOPIC
              value: "xbrl-instance-extracted"
            # - name: BOOTSTRAP_SERVER
            #   valueFrom:
            #     secretKeyRef:
            #       name: api-secrets
            #       key: bootstrap_server