apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-demo-consumer-scaledobject
  namespace: default
  labels:
    deploymentName: keda-demo-consumer-deployment
spec:
  scaleTargetRef:
    name: keda-demo-consumer-deployment
  pollingInterval: 5
  minReplicaCount: 1
  maxReplicaCount: 5  # Max can go upto num of partitions you have in the topic
  triggers:
    - type: kafka
      metadata:
        consumerGroup: generate-report-service-consumer-group
        bootstrapServers: host.docker.internal:9092
        topic: xbrl-instance-extracted
        lagThreshold: "5"
        offsetRestPolicy: latest
        # sasl: plaintext
        # tls: enable
      # authenticationRef:
      #   name: keda-kafka-credentials